version: "3.7"

services:
  pydiocells:
    image: pydio/cells:latest
    container_name: pydiocells
    hostname: pydiocells
    expose:
      - 443
    volumes:
      - ${CONFIG_DIR}/pydio-cells/config:/var/cells
      - ${CONFIG_DIR}/pydio-cells/data:/data
      - ${CONFIG_DIR}/pydio-cells/metrics:/var/cells/services/pydio.gateway.metrics
    environment:
      - CELLS_WORKING_DIR=/var/cells
      - CELLS_DATA=/data
      - CELLS_BIND=${APP_URL}:443
      - CELLS_EXTERNAL=https://${APP_URL}
      - CELLS_ENABLE_METRICS=true
      - CELLS_METRICS_BASIC_AUTH=${METRICS_ADMIN_USER}:${METRICS_ADMIN_PASS}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pydiocells.rule=Host(`${APP_URL}`)"
      - "traefik.http.routers.pydiocells.entrypoints=websecure"
      - "traefik.http.routers.pydiocells.tls.certresolver=tlsresolver"
      - "traefik.http.services.pydiocells.loadbalancer.server.scheme=https"
      - "traefik.http.routers.pydiocells.middlewares=authelia@docker"
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped
